HopkinsIDD/covid-dashboard-app

- src/components/Filters/Buttons.js
- src/components/Filters/Overlays.js
- src/components/Filters/Scenarios.js
- src/components/Filters/Severity.js
- src/components/Filters/Sliders.js
- src/components/Graph/Graph.js
- src/components/Graph/Legend.js
- src/components/Graph/ThresholdLabel.js
- src/components/MainContainer.js
- src/index.css
- src/store/constants.js
- src/utils/utils.js
Update threshold flag function
Add sim threshold legend
Add data threshold picker
> Stat threshold

- package-lock.json
- package.json
- src/components/Filters/Brush.js
- src/components/Filters/Scenarios.js
- src/components/Filters/Severity.js
- src/components/Filters/SeverityContainer.js
- src/components/Filters/Sliders.js
- src/components/Graph/Graph.js
- src/components/Graph/GraphContainer.js
- src/components/Graph/ThresholdLabel.js
- src/components/MainContainer.js
- src/index.css
Add multiple severity components and bind to scenarios
> Severity menu

- .gitignore
- src/components/Chart/Chart.js
- src/components/Chart/ChartContainer.js
- src/components/Chart/ChartLegend.js
- src/components/Chart/DatePicker.js
- src/components/Chart/IndicatorSelection.js
- src/components/Chart/SummaryLabel.js
- src/components/Filters/Brush.js
- src/components/Filters/R0.js
- src/components/Filters/Scenarios.js
- src/components/Filters/SeverityContainer.js
- src/components/Filters/Sliders.js
- src/components/Graph/Graph.js
- src/components/Graph/GraphContainer.js
- src/components/Graph/GraphFilter.js
- src/components/Graph/ThresholdLabel.js
- src/components/MainContainer.js
- src/components/Map/DateSlider.js
- src/components/Map/Map.js
- src/components/Map/MapContainer.js
- src/index.css
Prevent user from deselecting an R0 range
> Prevent user from deselecting an R0 range

- src/components/Chart/Chart.js
- src/components/Chart/IndicatorSelection.js
- src/components/Chart/ScaleToggle.js
- src/components/Filters/R0.js
- src/components/Filters/Severity.js
- src/components/Filters/SeverityContainer.js
- src/components/Filters/Sliders.js
- src/components/Filters/Switch.js
- src/components/Graph/MainGraph.js
- src/index.css
- src/utils/constants.js
- Add radio buttons for user to select between
- Disable threshold menu when confidence is selected
Closes #26
> User can select between exceedence and confidence

- LICENSE.txt
- package.json
- src/components/Chart/ChartContainer.js
- src/components/Graph/GraphContainer.js
- src/components/Graph/Legend.js
- src/components/Graph/MainGraph.js
- src/components/Graph/ThresholdLabel.js
- src/components/MainContainer.js
- src/components/Map/MainMap.js
- src/components/Map/Map.js
- src/components/NavBar.js
- src/components/Search/Search.js
- src/index.css
- src/utils/constants.js
Changes to make svg render correctly on mobile devices.
Fixes #60 , #35
> Mobile svg

- src/index.css
fixes height jump on severities hover if two scenarios are selected
> Severities hover bug

- src/components/Chart/Chart.js
> Fix Disappearing Chart Tooltips

- src/components/Map/MapContainer.js
fixing a small issue for the synchronized map zoom so that the paths update thickness as you zoom
> updating path strokes on zoom

- src/components/Chart/MainChart.js
- src/components/Filters/Scenarios.tsx
- src/components/Filters/SeverityContainer.tsx
- src/components/Graph/MainGraph.js
- src/components/Map/MainMap.js
- src/utils/constantsTypes.tsx
- tsconfig.json
@lxu213 
This PR migrates Scenarios.js -> Secanrios.tsx
TODOs:
> Migrate Scenarios to TS

- src/components/Chart/ChartContainer.js
- src/components/Filters/ModeToggle.tsx
- src/components/Filters/Scenarios.tsx
- src/components/Filters/SeverityContainer.tsx
- src/components/Graph/GraphContainer.js
- src/components/Graph/ThresholdLabel.tsx
- src/components/Map/MapContainer.js
- src/utils/constantsTypes.tsx
- src/utils/typeUtils.ts
@lxu213 
Migrate ThresholdLabel to TS
> Migrate ThresholdLabel to TS

- src/utils/constants.js
- src/utils/utils.js
Catch if there's missing data in actuals and statsForMap.
Updates our expected parameters to incidD, incidH, incidC
> Add catch in case of missing data

- src/components/Filters/ActualSwitch.tsx
- src/components/Graph/MainGraph.js
@BenjiLee 
Migrate ActualSwitch to TypeScript
> Migrate ActualSwitch to TS

- .github/workflows/s3.yml
- src/components/Map/MainMap.js
- src/utils/constants.js
Switch from `idd-dashboard-runs` to `idd-dashboard-runs-staging`
> Connect to staging s3 bucket

- src/components/Graph/MainGraph.js
Used to be the current date, changing the default threshold to the date scenario was run.
> changing dateThreshold default to scenario run date

- src/components/Filters/ActualSwitch.tsx
- src/components/Filters/Indicators.tsx
- src/components/Graph/Graph.js
- src/components/Graph/Legend.js
- src/components/Graph/MainGraph.js
- src/components/MainContainer.js
- src/utils/utils.js
> Fetch ground truth data from s3 bucket

- src/components/Graph/Graph.js
- src/components/Graph/MainGraph.js
> Set confBounds as default mode

- src/components/Graph/Graph.js
- src/components/Graph/Legend.js
> reverting to render actuals data as points without connecting line

- src/components/Graph/Graph.js
- src/components/Graph/GraphContainer.js
- src/components/Graph/Legend.js
- src/components/Graph/MainGraph.js
Added a line to visualize the date of the simulation run. Addresses #124
> Rundate line

- .github/workflows/s3.yml
- src/utils/constants.js
> Set relative bucket location

- package-lock.json
- package.json
- src/components/Chart/MainChart.js
- src/components/Graph/Graph.js
- src/components/Graph/MainGraph.js
- src/components/Map/MainMap.js
- src/components/ViewModal.js
- src/index.css
This is a first attempt at a reasonable lift to make the graph instructions something people have to read before interacting with the graph. This addresses Issue #131. @lxu213 can you take a look and let me know what you think? If you like it, I can implement for the Chart and Graph views.
> Modal for Instructions

- src/components/Graph/Graph.js
- src/components/Graph/MainGraph.js
> Conf bounds clipping

- src/components/Filters/Brush.js
- src/components/Graph/Graph.js
- src/components/Graph/MainGraph.js
> Brush colors

- src/components/Filters/Sliders.js
- src/components/Graph/Graph.js
- src/components/Graph/GraphContainer.js
- src/components/Graph/MainGraph.js
- src/components/Graph/ThresholdLabel.tsx
- src/utils/utils.js
Fixes Issue #129 where Callout of Indicator Threshold above Graph not in sync with value on Threshold slider.
> Exceedence bug

- src/components/Chart/MainChart.js
- src/components/Graph/MainGraph.js
- src/components/MainContainer.js
- src/components/Map/MainMap.js
- src/index.css
> Fetch fails gracefully with error information

- src/components/Graph/ThresholdLabel.tsx
> fixed threshold default bug

- src/utils/threshold.js
> Fixing threshold sim coloring

- README.md
- src/scripts/validate.py
> Add size limit validation to validator.py
